### ISSUE TITLE
volume first mount should be empty

### ISSUE THREAD

**Issue by alipay404** [juicedata/docker-volume-juicefs#22]
first mount the directory is not empty, such as some juicefs config files, then docker do not copy container files to volumes,

**Comment by zwwhdls** [comment]
Hi @alipay404 , can you provide the steps to reproduce it?

**Comment by alipay404** [comment]
> Hi @alipay404 , can you provide the steps to reproduce it?

```
// docker-compose.yml
version: "3.8"

services:
  nginx:
    image: nginx
    volumes:
      - xxx:/usr/share/nginx/html
volumes:
  xxx:
    driver: juicefs
    driver_opts:
      name: xxx
      metaurl: ---
      access-key: ---
      secret-key: ---
```

then you will get /usr/share/nginx/html is empty, but when I use local volume it will be not empty
