### ISSUE TITLE
mysql init failure with juicefs volume

### ISSUE THREAD

**Issue by edwardchenchen** [juicedata/docker-volume-juicefs#26]
I have created a volume using 
```
juicefs format \
    --storage minio \
    --bucket "https://minio.edwardcc.com/juicefs" \
    --access-key python \
    --secret-key removed \
    "mysql://root:password@(removed:3306)/juicefs" \
    docker
```
format success
```
2022/10/11 16:21:12.119184 juicefs[15272] <INFO>: Meta address: mysql://root:****@(removed:3306)/juicefs [interface.go:402]
2022/10/11 16:21:12.128931 juicefs[15272] <INFO>: Data use minio://minio.edwardcc.com/juicefs/docker/ [format.go:435]
2022/10/11 16:21:12.947961 juicefs[15272] <INFO>: Volume is formatted as {
  "Name": "docker",
  "UUID": "30444015-1d19-4865-923c-b7b618d69143",
  "Storage": "minio",
  "Bucket": "https://minio.edwardcc.com/juicefs",
  "AccessKey": "python",
  "SecretKey": "removed",
  "BlockSize": 4096,
  "Compression": "none",
  "KeyEncrypted": true,
  "TrashDays": 1,
  "MetaVersion": 1
} [format.go:472]
```

start a mysql db using compse
`docker-compose.yml`
```
version: '3'
services:
  db:
    image: mysql/mysql-server
    restart: always
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
      MYSQL_ROOT_PASSWORD: demo
    volumes:
      - jfsvolume:/var/lib/mysql
volumes:
  jfsvolume:
    driver: juicedata/juicefs:latest
    driver_opts:
      name: jfsvolume
      metaurl: "mysql://root:password@(removed:3306)/juicefs"
```
the mysql init process failed with 
<img width="857" alt=" 2022-10-11 at 16 25 15" src="https://user-images.githubusercontent.com/6397192/195006710-5b390b80-5b81-46d8-8339-09ee14248fee.png">
can see high volume of write to minio
<img width="1693" alt=" 2022-10-11 at 16 51 50" src="https://user-images.githubusercontent.com/6397192/195007280-af62b2a1-583f-4cb0-b7ec-aec5a1a7ca9c.png">

<img width="599" alt=" 2022-10-11 at 16 46 57" src="https://user-images.githubusercontent.com/6397192/195006601-62648777-9b6b-4bd1-96a0-7463798319e4.png">

I have also tried using AWS S3, same problem
