### ISSUE TITLE
Setting arbitrary environment variables for juicefs docker volume plugin

### ISSUE THREAD

**Issue by DavidGOrtega** [juicedata/docker-volume-juicefs#28]
## Creation
```sh
⠿ Volume "jfsvolume"  Error                                                                                         0.0s
Error response from daemon: create jfsvolume: VolumeDriver.Create: signal: segmentation fault
```

After a first error trial the volume will be falsely created via a cache folder but not connected to the S3 bucket. 

## Delete
Delete the volume is simply impossible

```sh
docker volume rm jfsvolume --force 
Error response from daemon: remove jfsvolume: VolumeDriver.Remove: exit status 1
``` 

## Test case

```yaml
version: '3.7'

x-shared: &shared
  image: alpine:3.14
  command: tail -F anything
  restart: unless-stopped
  networks:
    - demo
  volumes:
    - jfsvolume:/datavault

services:
  node1:
    <<: *shared

  node2:
    <<: *shared

networks:
  demo:

volumes:
  jfsvolume:
    driver: juicedata/juicefs
    driver_opts:
      name: datavault
      metaurl: redis://127.0.0.1:9190/1
      storage: s3
      bucket: https://s3.gra.perf.cloud.ovh.net/mybucket
      accesskey: XXX
      secretkey: XXX
```

**Comment by DavidGOrtega** [comment]
I have also tried R2 with the same outcome

```yaml
volumes:
  jfsvolume:
    driver: juicedata/juicefs
    driver_opts:
      name: datavault
      metaurl: redis://127.0.0.1:9190/2
      storage: s3
      bucket: https://YYY.r2.cloudflarestorage.com/mybucket
      accesskey: XXX
      secretkey: XXX
```

```sh
docker-compose up -d
[+] Running 0/1
 ⠿ Volume "zz_jfsvolume"  Error                                                                                             0.1s
Error response from daemon: create zz_jfsvolume5: VolumeDriver.Create: signal: segmentation fault
```

This is not working
